# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dlg_importar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlg_importar(object):
    def setupUi(self, dlg_importar):
        dlg_importar.setObjectName("dlg_importar")
        dlg_importar.resize(696, 469)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_importar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tw_datos = QtWidgets.QTableWidget(dlg_importar)
        self.tw_datos.setObjectName("tw_datos")
        self.tw_datos.setColumnCount(0)
        self.tw_datos.setRowCount(0)
        self.verticalLayout.addWidget(self.tw_datos)
        self.bbox_aceptarCancelar = QtWidgets.QDialogButtonBox(dlg_importar)
        self.bbox_aceptarCancelar.setOrientation(QtCore.Qt.Horizontal)
        self.bbox_aceptarCancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbox_aceptarCancelar.setObjectName("bbox_aceptarCancelar")
        self.verticalLayout.addWidget(self.bbox_aceptarCancelar)

        self.retranslateUi(dlg_importar)
        self.bbox_aceptarCancelar.accepted.connect(dlg_importar.accept) # type: ignore
        self.bbox_aceptarCancelar.rejected.connect(dlg_importar.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlg_importar)

    def retranslateUi(self, dlg_importar):
        _translate = QtCore.QCoreApplication.translate
        dlg_importar.setWindowTitle(_translate("dlg_importar", "Dialog"))
