# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ventanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaPrincipal(object):
    def setupUi(self, ventanaPrincipal):
        ventanaPrincipal.setObjectName("ventanaPrincipal")
        ventanaPrincipal.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(ventanaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_mes = QtWidgets.QLabel(self.centralwidget)
        self.lbl_mes.setObjectName("lbl_mes")
        self.horizontalLayout.addWidget(self.lbl_mes)
        self.dte_mes = QtWidgets.QDateEdit(self.centralwidget)
        self.dte_mes.setMinimumSize(QtCore.QSize(90, 0))
        self.dte_mes.setCalendarPopup(True)
        self.dte_mes.setObjectName("dte_mes")
        self.horizontalLayout.addWidget(self.dte_mes)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_gastos = QtWidgets.QLabel(self.centralwidget)
        self.lbl_gastos.setObjectName("lbl_gastos")
        self.verticalLayout.addWidget(self.lbl_gastos)
        self.tw_gastos = QtWidgets.QTableWidget(self.centralwidget)
        self.tw_gastos.setObjectName("tw_gastos")
        self.tw_gastos.setColumnCount(0)
        self.tw_gastos.setRowCount(0)
        self.verticalLayout.addWidget(self.tw_gastos)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.wgt_grafico = MplCanvas(self.centralwidget)
        self.wgt_grafico.setMinimumSize(QtCore.QSize(350, 0))
        self.wgt_grafico.setObjectName("wgt_grafico")
        self.horizontalLayout_2.addWidget(self.wgt_grafico)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        ventanaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ventanaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        self.menu_Archivo = QtWidgets.QMenu(self.menubar)
        self.menu_Archivo.setObjectName("menu_Archivo")
        self.menu_Importar = QtWidgets.QMenu(self.menu_Archivo)
        self.menu_Importar.setObjectName("menu_Importar")
        ventanaPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ventanaPrincipal)
        self.statusbar.setObjectName("statusbar")
        ventanaPrincipal.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ventanaPrincipal)
        self.toolBar.setObjectName("toolBar")
        ventanaPrincipal.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionArchivo_de_movimientos_del_Banco_Nacional = QtWidgets.QAction(ventanaPrincipal)
        self.actionArchivo_de_movimientos_del_Banco_Nacional.setObjectName("actionArchivo_de_movimientos_del_Banco_Nacional")
        self.actionArchivo_de_movimientos_de_BAC_Credomatic = QtWidgets.QAction(ventanaPrincipal)
        self.actionArchivo_de_movimientos_de_BAC_Credomatic.setObjectName("actionArchivo_de_movimientos_de_BAC_Credomatic")
        self.menu_Importar.addAction(self.actionArchivo_de_movimientos_del_Banco_Nacional)
        self.menu_Importar.addAction(self.actionArchivo_de_movimientos_de_BAC_Credomatic)
        self.menu_Archivo.addAction(self.menu_Importar.menuAction())
        self.menubar.addAction(self.menu_Archivo.menuAction())
        self.toolBar.addAction(self.actionArchivo_de_movimientos_del_Banco_Nacional)
        self.toolBar.addAction(self.actionArchivo_de_movimientos_de_BAC_Credomatic)
        self.lbl_mes.setBuddy(self.dte_mes)
        self.lbl_gastos.setBuddy(self.tw_gastos)

        self.retranslateUi(ventanaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipal)

    def retranslateUi(self, ventanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        ventanaPrincipal.setWindowTitle(_translate("ventanaPrincipal", "MainWindow"))
        self.lbl_mes.setText(_translate("ventanaPrincipal", "Mes: "))
        self.dte_mes.setDisplayFormat(_translate("ventanaPrincipal", "MM/yyyy"))
        self.lbl_gastos.setText(_translate("ventanaPrincipal", "Gastos"))
        self.menu_Archivo.setTitle(_translate("ventanaPrincipal", "&Archivo"))
        self.menu_Importar.setTitle(_translate("ventanaPrincipal", "&Importar"))
        self.toolBar.setWindowTitle(_translate("ventanaPrincipal", "toolBar"))
        self.actionArchivo_de_movimientos_del_Banco_Nacional.setText(_translate("ventanaPrincipal", "Archivo de movimientos del Banco Nacional"))
        self.actionArchivo_de_movimientos_de_BAC_Credomatic.setText(_translate("ventanaPrincipal", "Archivo de movimientos de BAC Credomatic"))
from ui_MplCanvas import MplCanvas


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaPrincipal = QtWidgets.QMainWindow()
    ui = Ui_ventanaPrincipal()
    ui.setupUi(ventanaPrincipal)
    ventanaPrincipal.show()
    sys.exit(app.exec_())
